### ISSUE TITLE
Awesome Book issues.

### ISSUE THREAD

**Issue by maximoortelli** [maximoortelli/Awesome-Book#4]
_Awesome Books: A complete website with navigation is an exercise in which I will take the Awesome books application and convert it into a fully functional website. I will refactor the project to add three new sections on top of the two sections, i have already completed: Books list (done), Add book form (done), a new Contact info section, a Navigation bar, and a Footer. The goal here is to master all of the tools and best practices learned about in previous steps to use them in all Microverse projects and most likely in my future job as well._

**Comment by gilberthappi** [comment]
you done good job Bro

**Comment by ALPANNA-GH** [comment]
I have nothing to mention in your project
just well done 👍

**Comment by smas0900** [comment]
You did everything as per requirment
Good job
